//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopZooKalininWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id_zakaz { get; set; }
        public System.DateTime Data { get; set; }
        public int Kolichestvo { get; set; }
        public int id_product { get; set; }
        public int id_users { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
